language: clojure
lein: lein
jdk:
- openjdk8
before_install:
- git config --global user.email "ohyecloudy@gmail.com"
- git config --global user.name "ohyecloudy"
install:
- set -e
- git clone https://$GH_TOKEN@github.com/ohrepos/pquotes-repo.git --branch=gh-pages result
- git clone https://github.com/ohyecloudy/tbot-quote-builder.git builder
- cd builder;lein uberjar
script:
- cd ..;java -jar ./builder/target/tbot-quote-builder-standalone.jar -s ./src/q-src.clj -o ./result/quotes -b http://ohrepos.github.io/pquotes-repo/quotes/ -t @book_quote_bot
after_success:
- set -e
- cd result
- git remote rm origin
- git remote add origin https://$GH_TOKEN@github.com/ohrepos/pquotes-repo.git
- git add -f .
- git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to gh-pages"
- git push -fq origin gh-pages
env:
  global:
  - secure: "Ews1m6r8WyOy0KVJr8j09WtDb1x+EBdfVKnAzSUwAeulGi/ddUsosuJjrZEg2iFq0NPYiL/emPc5fsY24If16utebrBgk0eu+cBaaMOll0XJ0g+P87xjeeDL7rLDwVB6lqLVauDvVLjO3s7qi1Zuhh9a9c2DJOqUnrBsyTSb+Ic="
